package BusTransportSystem.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_Point extends EnumerationDescriptorBase {

  public EnumerationDescriptor_Point() {
    super(0x424422c1d3914c11L, 0x972cef618d3c579bL, 0x13668af04e3ed857L, "Point", "r:ed66baf8-00a9-4ade-843c-5dadbf05f6b7(BusTransportSystem.structure)/1397957499054643287");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_ARRIVAL_POINT_0 = new EnumerationDescriptor.MemberDescriptor("ARRIVAL_POINT", "ARRIVAL_POINT", 0x13668af04e3ed858L, "r:ed66baf8-00a9-4ade-843c-5dadbf05f6b7(BusTransportSystem.structure)/1397957499054643288");
  private final EnumerationDescriptor.MemberDescriptor myMember_DEPARTURE_POINT_0 = new EnumerationDescriptor.MemberDescriptor("DEPARTURE_POINT", "DEPARTURE_POINT", 0x13668af04e3ed859L, "r:ed66baf8-00a9-4ade-843c-5dadbf05f6b7(BusTransportSystem.structure)/1397957499054643289");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x424422c1d3914c11L, 0x972cef618d3c579bL, 0x13668af04e3ed857L, 0x13668af04e3ed858L, 0x13668af04e3ed859L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_ARRIVAL_POINT_0, myMember_DEPARTURE_POINT_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "ARRIVAL_POINT":
        return myMember_ARRIVAL_POINT_0;
      case "DEPARTURE_POINT":
        return myMember_DEPARTURE_POINT_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
