package BusTransportSystem.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_DataType extends EnumerationDescriptorBase {

  public EnumerationDescriptor_DataType() {
    super(0x424422c1d3914c11L, 0x972cef618d3c579bL, 0x13668af04e3ed877L, "DataType", "r:ed66baf8-00a9-4ade-843c-5dadbf05f6b7(BusTransportSystem.structure)/1397957499054643319");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_BIG_DECIMAL_0 = new EnumerationDescriptor.MemberDescriptor("BIG_DECIMAL", "BIG_DECIMAL", 0x13668af04e3ed878L, "r:ed66baf8-00a9-4ade-843c-5dadbf05f6b7(BusTransportSystem.structure)/1397957499054643320");
  private final EnumerationDescriptor.MemberDescriptor myMember_DATE_0 = new EnumerationDescriptor.MemberDescriptor("DATE", "DATE", 0x13668af04e3ed885L, "r:ed66baf8-00a9-4ade-843c-5dadbf05f6b7(BusTransportSystem.structure)/1397957499054643333");
  private final EnumerationDescriptor.MemberDescriptor myMember_DATETIME_0 = new EnumerationDescriptor.MemberDescriptor("DATETIME", "DATETIME", 0x13668af04e3ed888L, "r:ed66baf8-00a9-4ade-843c-5dadbf05f6b7(BusTransportSystem.structure)/1397957499054643336");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x424422c1d3914c11L, 0x972cef618d3c579bL, 0x13668af04e3ed877L, 0x13668af04e3ed878L, 0x13668af04e3ed885L, 0x13668af04e3ed888L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_BIG_DECIMAL_0, myMember_DATE_0, myMember_DATETIME_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "BIG_DECIMAL":
        return myMember_BIG_DECIMAL_0;
      case "DATE":
        return myMember_DATE_0;
      case "DATETIME":
        return myMember_DATETIME_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
