package BusTransportSystem.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_PaymentMethod extends EnumerationDescriptorBase {

  public EnumerationDescriptor_PaymentMethod() {
    super(0x424422c1d3914c11L, 0x972cef618d3c579bL, 0x3608a2c259a3eab8L, "PaymentMethod", "r:ed66baf8-00a9-4ade-843c-5dadbf05f6b7(BusTransportSystem.structure)/3893540833473063608");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_CREDIT_CARD_0 = new EnumerationDescriptor.MemberDescriptor("CREDIT_CARD", "CREDIT_CARD", 0x3608a2c259a3eab9L, "r:ed66baf8-00a9-4ade-843c-5dadbf05f6b7(BusTransportSystem.structure)/3893540833473063609");
  private final EnumerationDescriptor.MemberDescriptor myMember_DEBIT_CARD_0 = new EnumerationDescriptor.MemberDescriptor("DEBIT_CARD", "DEBIT_CARD", 0x3608a2c259a3eac4L, "r:ed66baf8-00a9-4ade-843c-5dadbf05f6b7(BusTransportSystem.structure)/3893540833473063620");
  private final EnumerationDescriptor.MemberDescriptor myMember_BANK_TRANSFER_0 = new EnumerationDescriptor.MemberDescriptor("BANK_TRANSFER", "BANK_TRANSFER", 0x3608a2c259a3eac7L, "r:ed66baf8-00a9-4ade-843c-5dadbf05f6b7(BusTransportSystem.structure)/3893540833473063623");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x424422c1d3914c11L, 0x972cef618d3c579bL, 0x3608a2c259a3eab8L, 0x3608a2c259a3eab9L, 0x3608a2c259a3eac4L, 0x3608a2c259a3eac7L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_CREDIT_CARD_0, myMember_DEBIT_CARD_0, myMember_BANK_TRANSFER_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "CREDIT_CARD":
        return myMember_CREDIT_CARD_0;
      case "DEBIT_CARD":
        return myMember_DEBIT_CARD_0;
      case "BANK_TRANSFER":
        return myMember_BANK_TRANSFER_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
