package BusTransportSystem.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_BookingStatus extends EnumerationDescriptorBase {

  public EnumerationDescriptor_BookingStatus() {
    super(0x424422c1d3914c11L, 0x972cef618d3c579bL, 0x3608a2c259a3ea81L, "BookingStatus", "r:ed66baf8-00a9-4ade-843c-5dadbf05f6b7(BusTransportSystem.structure)/3893540833473063553");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_PENDING_0 = new EnumerationDescriptor.MemberDescriptor("PENDING", "PENDING", 0x3608a2c259a3ea82L, "r:ed66baf8-00a9-4ade-843c-5dadbf05f6b7(BusTransportSystem.structure)/3893540833473063554");
  private final EnumerationDescriptor.MemberDescriptor myMember_APPROVED_0 = new EnumerationDescriptor.MemberDescriptor("APPROVED", "APPROVED", 0x3608a2c259a3ea83L, "r:ed66baf8-00a9-4ade-843c-5dadbf05f6b7(BusTransportSystem.structure)/3893540833473063555");
  private final EnumerationDescriptor.MemberDescriptor myMember_CANCELLED_0 = new EnumerationDescriptor.MemberDescriptor("CANCELLED", "CANCELLED", 0x3608a2c259a3ea86L, "r:ed66baf8-00a9-4ade-843c-5dadbf05f6b7(BusTransportSystem.structure)/3893540833473063558");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x424422c1d3914c11L, 0x972cef618d3c579bL, 0x3608a2c259a3ea81L, 0x3608a2c259a3ea82L, 0x3608a2c259a3ea83L, 0x3608a2c259a3ea86L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_PENDING_0, myMember_APPROVED_0, myMember_CANCELLED_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "PENDING":
        return myMember_PENDING_0;
      case "APPROVED":
        return myMember_APPROVED_0;
      case "CANCELLED":
        return myMember_CANCELLED_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
