package BusTransportSystem.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Adult = 0;
  public static final int Baggage = 1;
  public static final int Booking = 2;
  public static final int Bus = 3;
  public static final int Child = 4;
  public static final int City = 5;
  public static final int KIOSK = 6;
  public static final int OnlinePayment = 7;
  public static final int Passenger = 8;
  public static final int Payment = 9;
  public static final int Seat = 10;
  public static final int Ticket = 11;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x424422c1d3914c11L, 0x972cef618d3c579bL);
    builder.put(0x3608a2c259a3eab0L, Adult);
    builder.put(0x5fc8001b1615e1dL, Baggage);
    builder.put(0x3608a2c259a3ea79L, Booking);
    builder.put(0x13668af04e3e54ebL, Bus);
    builder.put(0x3608a2c259a3eaa4L, Child);
    builder.put(0x13668af04e3ed84dL, City);
    builder.put(0x3608a2c259a3eaceL, KIOSK);
    builder.put(0x3608a2c259a3eacbL, OnlinePayment);
    builder.put(0x3608a2c259a3ea93L, Passenger);
    builder.put(0x3608a2c259a3eab5L, Payment);
    builder.put(0x13668af04e3ed848L, Seat);
    builder.put(0x13668af04e3ed872L, Ticket);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
